services:
  webapp:
    build: .
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - postgres
    profiles:
      - all

  postgres:
    container_name: webapp_postgres
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - backend
      - postgres
    volumes:
      - webapp_pgdata:/var/lib/postgresql/data
    profiles:
      - postgres
      - all
  
  pgadmin:
    container_name: webapp_pgadmin
    image: dpage/pgadmin4:8.10
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5431:80"
    networks:
      - postgres
    volumes:
      - webapp_pgadmindata:/var/lib/pgadmin
    depends_on:
      - postgres
    profiles:
      - postgres
      - all

volumes:
  webapp_pgdata: {}
  webapp_pgadmindata: {}

networks:
  backend:
  postgres:
